#include "amod.h"

DLL_EXPORT struct questlog game_questlog[] = {
    {0,  "Lydia's Potion",              1,   2,   "James",         "Cameron",          1},
    {1,  "Find the Magic Item",         2,   3,   "Gwendylon",     "Cameron",          2},
    {2,  "The Second Skull",            3,   5,   "Gwendylon",     "Cameron",          3},
    {3,  "The Third Skull",             5,   7,   "Gwendylon",     "Cameron",          4},
    {4,  "Kill the Foul Magician",      6,   8,   "Gwendylon",     "Cameron",          6},
    {5,  "Bear Hunt",                   6,   8,   "Yoakin",        "Cameron",          9},
    {6,  "A Fool's Request",            6,   8,   "Nook",          "Cameron",          5},
    {7,  "Mages Gone Berserk",          6,   9,   "Guiwynn",       "Cameron",          7},
    {8,  "The Recipe for Happiness",    7,   10,  "Guiwynn",       "Cameron",          8},
    {9,  "Knightly Troubles",           7,   10,  "Logain",        "Cameron",          9},
    {10, "Loisan's House",              9,   12,  "Seymour",       "Aston",            10},
    {11, "The Silver Skull",            10,  13,  "Seymour",       "Aston",            11},
    {12, "Find Loisan",                 11,  15,  "Seymour",       "Aston",            12},
    {13, "Jeepers Creepers",            12,  18,  "Kelly",         "Aston",            15},
    {14, "Underground Park Shrines",    15,  20,  "Kelly",         "Aston",            17},
    {15, "In Search of Clara",          20,  27,  "Kelly",         "Aston",            23},
    {16, "The Astronomer's Notes",      15,  20,  "Gerassimo",     "Aston",            17},
    {17, "The Unwanted Tenants",        9,   12,  "Reskin",        "Cameron",          10},
    {18, "The Toughest Monster",        20,  25,  "Sir Jones",     "Aston",            22},
    {19, "The Toughestest Monster",     20,  26,  "Sir Jones",     "Aston",            23},
    {20, "Wanted: Occult Staff",        30,  36,  "Carlos",        "Aston",            33},
    {21, "Slay the Swampbeast",         23,  30,  "Clara",         "Swamp",            26},
    {22, "Impish Bear Hunt",            20,  27,  "William/Imp",   "Forest",           23},
    {23, "Praying Mantis Stew",         20,  27,  "William",       "Forest",           24},
    {24, "The Spider Queen",            25,  30,  "Hermit",        "Forest",           27},
    {25, "Earning the Lockpick",        25,  30,  "Guildmaster",   "Exkordon",         0},
    {26, "Extortion",                   25,  30,  "Guildmaster",   "Exkordon",         0},
    {27, "Price Fix Exposed",           25,  30,  "Guildmaster",   "Exkordon",         27},
    {28, "The Golden Lockpick",         26,  33,  "Guildmaster",   "Exkordon",         29},
    {29, "Dirty Hands",                 26,  33,  "Sanwyn",        "Exkordon",         0},
    {30, "The Old Governor's Cross",    33,  40,  "Skeleton",      "Exkordon",         36},
    {31, "Spider Poison",               30,  40,  "Cervik",        "Exkordon",         35},
    {32, "Join the Tribe",              63,  80,  "Kalanur",       "Nomad Plains",     70},
    {33, "Searching Sarkilar",          63,  80,  "Kir Laas",      "Nomad Plains",     70},
    {34, "A Golden Statue",             72,  90,  "Kir Garan",     "Nomad Plains",     80},
    {35, "Smuggler Book",               14,  17,  "Imp. Commander","Below Aston 2",    15},
    {36, "Contraband",                  14,  17,  "Imp. Commander","Below Aston 2",    0},
    {37, "Smuggler Leader",             14,  17,  "Imp. Commander","Below Aston 2",    15},
    {38, "The Family Heirloom",         32,  40,  "Aristocrat",    "Bran. Forest",     36},
    {39, "Bear Hunt - Again",           32,  36,  "Yoatin",        "Bran. Forest",     34},
    {40, "The Jewels of Brannington",   30,  36,  "Count B.",      "Brannington",      0},
    {41, "A Grolm's Spoils",            33,  42,  "Brenneth",      "Brannington",      37},
    {42, "A Thief's Loot",              33,  42,  "Brenneth",      "Brannington",      37},
    {43, "A Necromancer's Notes",       33,  42,  "Brenneth",      "Brannington",      37},
    {44, "A Rest Disturbed",            36,  43,  "Spirit",        "Brannington",      39},
    {45, "Searching a Miner's Tool",    42,  48,  "Broklin",       "Brannington",      45},
    {46, "A Miner's Vengeance",         44,  50,  "Broklin",       "Brannington",      47},
    {47, "A Miner's Misery",            85,  95,  "Dwarven Chief", "Grimroot",         90},
    {48, "A Miner's Bane",              95,  105, "Dwarven Chief", "Grimroot",         100},
    {49, "A Miner's Anguish",           105, 115, "Dwarven Chief", "Grimroot",         110},
    {50, "A Miner Lost",                115, 125, "Dwarven Chief", "Grimroot",         120},
    {51, "Lizard's Teeth",              95,  105, "Dwarven Shaman","Grimroot",         100},
    {52, "Collecting Berries",          100, 110, "Dwarven Shaman","Grimroot",         105},
    {53, "Elitist Head",                105, 115, "Dwarven Shaman","Grimroot",         110},
    {54, "Looking for Caligar",         55,  65,  "Kelly",         "Aston",            60},
    {55, "Fighting Styles",             55,  65,  "Glori",         "Caligar",          60},
    {56, "Obelisk Hunt",                55,  65,  "Glori",         "Caligar",          60},
    {57, "Find the Keyparts",           55,  65,  "Glori",         "Caligar",          60},
    {58, "Assemble the Key",            55,  65,  "Glori",         "Caligar",          60},
    {59, "Amazon Invaders",             55,  65,  "Homdem",        "Caligar",          60},
    {60, "The Emperor's Plaque",        55,  65,  "Kelly",         "Aston",            63},
    {61, "The Imperial Vault",          26,  28,  "Carlos",        "Aston",            27},
    {62, "Tunnel Magics",               26,  28,  "Rouven",        "Imperial Vault",   27},
    {63, "Chronicles of Seyan",         26,  28,  "Rouven",        "Imperial Vault",   27},
    {64, "Finding Arkhata",             48,  58,  "Guard",         "Brannington",      53},
    {65, "Rammy's Crown",               50,  60,  "Rammy",         "Arkhata",          55},
    {66, "Ishtar's Bracelet",           50,  60,  "Jaz",           "Arkhata",          55},
    {67, "Queen Fiona's Ring",          55,  65,  "Queen Fiona",   "Arkhata",          60},
    {68, "A Shopkeeper's Fright",       58,  68,  "Ramin",         "Arkhata",          63},
    {69, "The Monks' Request",          58,  68,  "Johnatan",      "Arkhata",          63},
    {70, "The Book Eater",              58,  68,  "Tracy",         "Arkhata",          63},
    {71, "Entrance Passes",             58,  66,  "Rammy",         "Arkhata",          62},
    {72, "The Source",                  70,  80,  "Jada",          "Arkhata",          75},
    {73, "Ceremonial Pot",              52,  62,  "Pot Maker",     "Arkhata",          57},
    {74, "The Lost Secrets",            52,  62,  "Thai Pan",      "Arkhata",          57},
    {75, "A Kidnapped Student",         63,  73,  "Trainer",       "Arkhata",          68},
    {76, "The Traitors",                60,  70,  "Clerk",         "Arkhata",          65},
    {77, "The Blue Harpy",              58,  68,  "Hunter",        "Arkhata",          63},
    {78, "The Mysterious Language",     60,  65,  "Johnatan",      "Arkhata",          62},
};
DLL_EXPORT int game_questcount = ARRAYSIZE(game_questlog);
